// THIS FILE HAS BEEN AUTO-GENERATED BY THE 'DEAR BINDINGS' GENERATOR.
// **DO NOT EDIT DIRECTLY**
// https://github.com/dearimgui/dear_bindings

#include "imgui.h"
#include "imgui_impl_opengl3.h"

#include <stdio.h>

// Wrap this in a namespace to keep it separate from the C++ API
// This define prevents #defines in the header getting defined again (as they are already in the normal header above),
// and thus generating redefinition warnings
#define DEAR_BINDINGS_INTERNAL_GLUE_CODE
namespace cimgui
{
#include "dcimgui_impl_opengl3.h"
}
#undef DEAR_BINDINGS_INTERNAL_GLUE_CODE

// By-value struct conversions

// Function stubs

#ifndef IMGUI_DISABLE

CIMGUI_IMPL_API bool cimgui::cImGui_ImplOpenGL3_Init(void)
{
    return ::ImGui_ImplOpenGL3_Init();
}

CIMGUI_IMPL_API bool cimgui::cImGui_ImplOpenGL3_InitEx(const char* glsl_version)
{
    return ::ImGui_ImplOpenGL3_Init(glsl_version);
}

CIMGUI_IMPL_API void cimgui::cImGui_ImplOpenGL3_Shutdown(void)
{
    ::ImGui_ImplOpenGL3_Shutdown();
}

CIMGUI_IMPL_API void cimgui::cImGui_ImplOpenGL3_NewFrame(void)
{
    ::ImGui_ImplOpenGL3_NewFrame();
}

CIMGUI_IMPL_API void cimgui::cImGui_ImplOpenGL3_RenderDrawData(cimgui::ImDrawData* draw_data)
{
    ::ImGui_ImplOpenGL3_RenderDrawData(reinterpret_cast<::ImDrawData*>(draw_data));
}

CIMGUI_IMPL_API bool cimgui::cImGui_ImplOpenGL3_CreateDeviceObjects(void)
{
    return ::ImGui_ImplOpenGL3_CreateDeviceObjects();
}

CIMGUI_IMPL_API void cimgui::cImGui_ImplOpenGL3_DestroyDeviceObjects(void)
{
    ::ImGui_ImplOpenGL3_DestroyDeviceObjects();
}

CIMGUI_IMPL_API void cimgui::cImGui_ImplOpenGL3_UpdateTexture(ImTextureData* tex)
{
    ::ImGui_ImplOpenGL3_UpdateTexture(tex);
}

#endif // #ifndef IMGUI_DISABLE
