name: Publish to JSR

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: build
          merge-multiple: true

      - run: ls -lah build

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          cache: 'npm'

      - name: Publish JSR
        run: npx jsr publish
